services:
  db-movies:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data
  db-adminer:
    image: adminer
    restart: always
    ports:
      - $ADMINER_PORT:$ADMINER_PORT

volumes:
  postgres_data:
